### ISSUE TITLE
Add custom IEPNB Favicon

### ISSUE THREAD

**Issue by mjanez** [OpenDataGIS/ckan-docker-iepnb#16]
Update IEPNB CKAN favicon to: 

![](https://des.iepnb.es/core/misc/favicon.ico)
`https://des.iepnb.es/core/misc/favicon.ico`

### Solution
Add to [`.env.example`](https://github.com/OpenDataGIS/ckan-docker-iepnb/blob/master/.env.example)

```ini
CKAN__FAVICON = https://des.iepnb.es/core/misc/favicon.ico
```

**Comment by dsanjurjo** [comment]
Done, but instead of reference the favicon file in the Iepnb site, it is included in the iepnb plugin.
